name: CI + SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest        # ← НЕ macos! Быстрее и дешевле

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python + uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          make install   # или: uv sync --all-extras --dev

      - name: Run tests with coverage
          env:
            SECRET_KEY: "django-insecure-for-ci-only-1234567890abcdef"   # ← вот так!
          run: |
            uv run pytest --cov=task_manager --cov-report=xml:coverage.xml --junitxml=junit.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master   # ← правильный экшен!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=pilgrim-nord_python-project-52
            -Dsonar.organization=pilgrim-nord-1
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=.
            -Dsonar.python.version=3.13